### ISSUE TITLE
Built markdown to docx but failed to attach an image file which is located in the same folder with md file

### ISSUE THREAD

**Issue by yeoupooh** [CodeVanguard/PanDoc-for-Azure-Pipelines#2]
Hi, 
Here is my markdown document:
```
# blah
![](myimage.png)
```
and the pipeline script below:
```
pool:
  vmImage: windows-latest

jobs:
  job:
  steps:
  - task: RunPanDoc@1
    inputs:
      sourceFile: '$(Build.SourcesDirectory)\mydocument.md'
      inputFormat: 'gfm'
      outputFormat: 'docx'
      destFile: '$(Build.SourcesDirectory)\mydocument.docx'

```
and the pipeline logs below:
```
...
Local variable information:
SourceFile  = 	D:\a\1\s\mydocument.md
InputFormat  = 	gfm
OutputFormat  = 	docx
DesinationFile   = 	D:\a\1\s\mydocument.docx
[WARNING] Could not fetch resource 'myimaage.png': PandocResourceNotFound "myimage.png"
Finishing: RunPanDoc
...
```
In the generated docx file, the image is not embedded.

Could you please help me to fix this issue?

Thank you in advance.
